### ISSUE TITLE
Macbook code

### ISSUE THREAD

**Issue by Majkl1337** [chrfyi/kju#5]
Hello I need help with this issue

Michael-MacBook-Pro:kju-master  michaelcerny$ node index.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

SyntaxError: /Users/michaelcerny/Desktop/kju-master /cookies.json: Unexpected token \ in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.Module._extensions..json (internal/modules/cjs/loader.js:797:27)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/michaelcerny/Desktop/kju-master /index.js:12:24)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by chrenn** [comment]
Make sure cookies.json is valid JSON, as stated in the error msg.

**Comment by Majkl1337** [comment]
Is that right?

<img width="1280" alt="Snímek obrazovky 2019-09-23 v 23 21 39" src="https://user-images.githubusercontent.com/47258477/65463964-1490cb80-de59-11e9-9a91-3bbb2ce7c6fc.png">

**Comment by chrenn** [comment]
What am I supposed to do with this screenshot? As stated in my previous comment, you probably made an error in step 3 while exporting the cookies. Please put in some effort yourself, I'm not doing support here.
